### ISSUE TITLE
Accessing formats

### ISSUE THREAD

**Issue by jqtrde** [CartoDB/cartodb-nodejs#24]
It's easy enough to use the SQL API to do something like `user.cartodb.com/api/v2/sql?format=SHP&q=SELECT * FROM tablename`

Being able to choose which format you'd like to view your data in is fantastic. How do I do that using this library?

Currently, `SELECT * FROM tablename` is giving me nice JSON output, but I'd also like the ability to download shapefiles when necessary. Is that possible?

**Comment by allthesignals** [comment]
It should at least allow for GeoJSON format. Maybe this is fixed in later versions.

**Comment by nerik** [comment]
https://github.com/CartoDB/cartodb-nodejs#sqlexecute
