### ISSUE TITLE
v0.5 sql.execute returns a string instead of JSON

### ISSUE THREAD

**Issue by clhenrick** [CartoDB/cartodb-nodejs#55]
after doing an `sql.execute()` a successful response returns a string, not parsed JSON. This is different behavior from v0.3.0 where it would return actual JSON.

**Comment by clhenrick** [comment]
cc @nerik

**Comment by nerik** [comment]
This was introduced when adding support for other formats than JSON. I just published a patch on NPM.

**Comment by clhenrick** [comment]
👍
