### ISSUE TITLE
resources domain needs to be updated

### ISSUE THREAD

**Issue by mikegiddens** [CartoDB/cartodb-nodejs#60]
As of today I believe the cartodb.com has been depracated and no longer works to make request and someone will need to update the cartodb.com/api/ to be carto.com/api/ in the /lib/resources.json file and then push the build to npm to allow people to upgrade and patch the problem.  This is a BREAKING issue and a hot fix should be released.

**Comment by dario1985** [comment]
@mikegiddens you can try to use #59 that fix this problem

**Comment by jaakla** [comment]
fixed by https://github.com/CartoDB/cartodb-nodejs/pull/62 - better late than never
